spring:
  datasource:
    url: jdbc:postgresql://localhost/db_upswing
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
hibernate:
  dialect: org.hibernate.dialect.HSQLDialect

#api:
#  security:
#    token:
#      secret: ${IP_UPSWING}