  spring:
    datasource:
      url: jdbc:postgresql://${DB_PATH}/${DATABASE}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
      format-sql: true
  hibernate:
    dialect: org.hibernate.dialect.HSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_UPSWING}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
    test-connection: true

#api:
#  security:
#    token:
#      secret: ${IP_UPSWING}